Tariff list
Lunex08/2019_android_git_reset_--hard pull request #12
Opened 2019-12-15 07:25 UTC by goddeuce1

2019-12-17 10:20 UTC, 102Rudy requested changes

2019-12-17 10:20 UTC, 102Rudy commented on .idea/.name
> +Analyzer
файлы из директории idea не должны быть в GIT

2019-12-17 10:20 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReuseable.java
> +        List<String> reusableDates = new ArrayList<>();
final

2019-12-17 10:20 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReuseable.java
> +                    List<CallHistoryRecord> callHistoryRecords = callsModule.getCalls();
final

2019-12-17 10:20 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReuseable.java
> +    class RecyclerAdapter extends RecyclerView.Adapter<RecyclerViewHolder> {
этот класс лучше положить в другой файл

2019-12-17 10:20 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReuseable.java
> +        private final List<String> dates;
лучше сделать класс, который будет содержать имя, телефон и дату, и использовать один List
использовать три источника данных, для того чтобы заполнить холдер - плохая практика

2019-12-17 10:20 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        gigs = usage / (1024f*1024f*1024f);
1024 - magic number

2019-12-17 10:20 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        Log.d("GIGS", String.valueOf(usage));
GIGS - magic string

2019-12-17 10:20 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/TariffsFragment.java
> +            private final List<Integer> icons;
уже писал об этом. Это очень плохо

2019-12-17 10:20 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/TariffsFragment.java
> +    private static List<Integer> tariffIcons;
зачем здесь статические листы?!

2019-12-17 10:20 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/TariffsFragment.java
> +        static class TariffAsyncTask extends AsyncTask<String, String, Void> {
AsyncTasks лучше не использовать) устаревший метод
Я бы взглянул в сторону Retrofit 2 для запросов в сеть - там будет из коробки хорошо работать
Но если хочется хардкора то лучше запилить реализацию на ExecutorService

2019-12-21 20:18 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReuseable.java
> +        List<String> reusableDates = new ArrayList<>();
Убрано вообще

2019-12-21 20:18 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReuseable.java
> +                    List<CallHistoryRecord> callHistoryRecords = callsModule.getCalls();
Поправил

2019-12-21 20:18 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReuseable.java
> +    class RecyclerAdapter extends RecyclerView.Adapter<RecyclerViewHolder> {
Поправил

2019-12-21 20:18 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReuseable.java
> +        private final List<String> dates;
Есть уже

2019-12-21 22:01 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/TariffsFragment.java
> +        static class TariffAsyncTask extends AsyncTask<String, String, Void> {
Retrofit 2 норм, удобная штука

2019-12-21 22:01 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/TariffsFragment.java
> +    private static List<Integer> tariffIcons;
Не актуально

2019-12-21 22:01 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/TariffsFragment.java
> +            private final List<Integer> icons;
Не актуально

2019-12-22 09:16 UTC, BrBrRoman commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        gigs = usage / (1024f*1024f*1024f);
Ну шо поделать. Их надо как-то считать

2019-12-22 09:19 UTC, BrBrRoman commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        Log.d("GIGS", String.valueOf(usage));
Сделано. Выкинул дебажный вывод

2019-12-22 09:23 UTC, BrBrRoman commented on .idea/.name
> +Analyzer
Судя по https://gitignore.io лишь некоторые директории и файлы из директории .idea должны быть исключены из git
![image](https://user-images.githubusercontent.com/32716489/71319941-c9b53d00-24b5-11ea-9fd7-8e3c4b88a002.png)

2019-12-22 09:39 UTC, 102Rudy approved these changes

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragment.java
> +public class DetailsFragment extends Fragment implements View.OnClickListener {
final class

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReusable.java
> +public class DetailsFragmentReusable extends Fragment {
final class

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
>  public class MainScreenFragment extends Fragment implements View.OnClickListener {
final class

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/TariffsFragment.java
> +        public Call<List<Post>> getAllPosts();
JSONPlaceHolderApi  это лучше разместить в отдельном файле

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/utils/NetworkService.java
> +    public static NetworkService getInstance() {
лучше использовать double check locking для потокобезопасности

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/utils/Post.java
> +    @Expose
Expose аннотация не обязательная, при стандартных настройках Gson serializer

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/utils/RecyclerAdapterReusable.java
> +    public static final String unknown_number = "Неизвестный";
этот текст лучше вынести в строковые ресурсы

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/utils/RecyclerAdapterReusable.java
> +    private final List<RecyclerDatasetReusable> data;
я бы назвал items а не data, кажется так понятнее

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/utils/RecyclerDatasetReusable.java
> +    public RecyclerDatasetReusable(String name, String phone, String date) {
NonNull/Nullable

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/utils/RecyclerDatasetReusable.java
> +    String getName() {
NonNull/Nullable

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/utils/RecyclerDatasetReusable.java
> +    String getPhone() {
NonNull/Nullable

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/utils/RecyclerDatasetReusable.java
> +    String getDate() {
NonNull/Nullable

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/utils/RecyclerViewHolderReusable.java
> +class RecyclerViewHolderReusable extends RecyclerView.ViewHolder {
а зачем Reusable в конце?

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/utils/TariffDataset.java
> +    public TariffDataset(String name, String gigabytes, String sms, String price, Integer icon) {
NonNull/Nullable

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/utils/TariffDataset.java
> +    String getName() {
NonNull/Nullable

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/utils/TariffDataset.java
> +    String getGigabytes() {
NonNull/Nullable

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/utils/TariffDataset.java
> +    String getSms() {
NonNull/Nullable

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/utils/TariffDataset.java
> +    String getPrice() { return this.price; }
NonNull/Nullable

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/res/layout/fragment_tariffs_item.xml
> +        android:id="@+id/tariffs_operator_icon"
лучше делать приставку в id:
для ImageView в начало добавлять iv
для TextView - tv
для Button - btn

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/utils/TariffAdapter.java
> +public class TariffAdapter extends RecyclerView.Adapter<TariffViewholder> {
final?

2019-12-22 09:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/utils/TariffAdapter.java
> +    private final List<TariffDataset> data;
можно назвать items - так более точно отражается сущность

2019-12-22 09:57 UTC, BrBrRoman commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        gigs = usage / (1024f*1024f*1024f);
Вынес выше в переменную - константу

2019-12-22 10:00 UTC, BrBrRoman commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
>  public class MainScreenFragment extends Fragment implements View.OnClickListener {
Done.

2019-12-22 10:00 UTC, BrBrRoman commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReusable.java
> +public class DetailsFragmentReusable extends Fragment {
Done.

2019-12-22 10:00 UTC, BrBrRoman commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragment.java
> +public class DetailsFragment extends Fragment implements View.OnClickListener {
Done.

2019-12-22 10:58 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/TariffsFragment.java
> +        public Call<List<Post>> getAllPosts();
Сделал

2019-12-22 11:00 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/utils/Post.java
> +    @Expose
Ок

2019-12-22 11:04 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/utils/RecyclerAdapterReusable.java
> +    private final List<RecyclerDatasetReusable> data;
Сделал

2019-12-22 11:04 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/utils/RecyclerDatasetReusable.java
> +    public RecyclerDatasetReusable(String name, String phone, String date) {
Сделал

2019-12-22 11:05 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/utils/RecyclerDatasetReusable.java
> +    String getName() {
Сделал

2019-12-22 11:05 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/utils/RecyclerDatasetReusable.java
> +    String getPhone() {
Сделал

2019-12-22 11:05 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/utils/RecyclerDatasetReusable.java
> +    String getDate() {
Сделал

2019-12-22 11:06 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/utils/TariffDataset.java
> +    public TariffDataset(String name, String gigabytes, String sms, String price, Integer icon) {
Сделал

2019-12-22 11:06 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/utils/TariffDataset.java
> +    String getName() {
Сделал

2019-12-22 11:06 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/utils/TariffDataset.java
> +    String getGigabytes() {
И это сделал

2019-12-22 11:06 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/utils/TariffDataset.java
> +    String getSms() {
да

2019-12-22 11:06 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/utils/TariffDataset.java
> +    String getPrice() { return this.price; }
сделал

2019-12-22 11:07 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/utils/TariffAdapter.java
> +public class TariffAdapter extends RecyclerView.Adapter<TariffViewholder> {
Теперь да

2019-12-22 11:08 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/utils/TariffAdapter.java
> +    private final List<TariffDataset> data;
Ага

2019-12-22 11:13 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/utils/NetworkService.java
> +    public static NetworkService getInstance() {
Да, сделал

2019-12-22 11:22 UTC, merged