Ui upper main screen fragment
Lunex08/2019_android_git_reset_--hard pull request #2
Opened 2019-11-13 18:04 UTC by goddeuce1

2019-11-14 19:39 UTC, 102Rudy requested changes

2019-11-14 19:39 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        cardView.setOnClickListener(new View.OnClickListener() {
лучше чтобы сам фрагмент имплементировал View.OnClickListener
а сюда передавать this

2019-11-14 19:39 UTC, 102Rudy commented on app/src/main/res/layout/main_screen_fragment.xml
> +                    android:text="Безлимитный"
хардкод ресурсов - плохая идея
для отображения в layout editor лучше использовать `tools:android`, и тогда можно хардкодить
в случае с `android:text` хардкодить нельзя

2019-11-14 19:39 UTC, 102Rudy commented on app/src/main/res/layout/main_screen_fragment.xml
> +                    android:text="Безлимитный"
комментарий касательно всего хардкода в этом файле

2019-11-15 11:23 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        cardView.setOnClickListener(new View.OnClickListener() {
Поправил

2019-11-15 16:05 UTC, goddeuce1 commented on app/src/main/res/layout/main_screen_fragment.xml
> +                    android:text="Безлимитный"
Поправил

2019-11-16 12:40 UTC, 102Rudy approved these changes

2019-11-16 12:53 UTC, merged