Ui main fragment graph
Lunex08/2019_android_git_reset_--hard pull request #5
Opened 2019-11-23 14:22 UTC by goddeuce1

2019-11-23 15:12 UTC, 102Rudy requested changes
need fixing

2019-11-23 15:12 UTC, 102Rudy commented on app/build.gradle
> +}
это не должно быть в этом файл. Это файл модуля, а репозитории надо добавлять в файл проекта

2019-11-23 15:12 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
>  public class MainScreenFragment extends Fragment implements View.OnClickListener {
final

2019-11-23 15:12 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        BarChart barChart = v.findViewById(R.id.main_graph);
final

2019-11-23 15:12 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        ArrayList<BarEntry> data = getData();
final List<BarEntry>

2019-11-23 15:12 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        BarDataSet barDataSet = new BarDataSet(data, "");
final

2019-11-23 15:12 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        BarData barData = new BarData(barDataSet);
final

2019-11-23 15:12 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        barDataSet.setColors(Color.RED);
может использовать более кастомные цвета?

2019-11-23 15:12 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        XAxis xAxis = barChart.getXAxis();
final

2019-11-23 15:12 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        barDataSet.setColors(Color.RED);
что нибудь из Material палитры цветов?

2019-11-23 15:12 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        String month = (String) DateFormat.format("MM", c);
final

2019-11-23 15:12 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        String day = (String) DateFormat.format("dd",   c);
здесь 2 или 3 лишний пробела перед `c);`

2019-11-23 15:12 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        ArrayList<String> datesList = new ArrayList<>();
final List

2019-11-23 15:12 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        for (int i = 6; i >= 0; --i) {
magic numbers нужно убрать

2019-11-23 15:12 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +    private ArrayList<BarEntry> getData(){
так, нужно использовать интерфейсы а не конкретные реализации.
Нужно поправить это во всем коде, больше писать об этом не буду

2019-11-23 15:12 UTC, 102Rudy commented on app/src/main/res/layout/main_screen_fragment.xml
>      <RelativeLayout
RelativeLayouts внутри RelativeLayout

2019-11-23 15:27 UTC, goddeuce1 commented on app/build.gradle
> +}
Исправил

2019-11-23 15:31 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        BarChart barChart = v.findViewById(R.id.main_graph);
Поправил

2019-11-23 15:39 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        ArrayList<BarEntry> data = getData();
Исправил

2019-11-23 15:41 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        BarDataSet barDataSet = new BarDataSet(data, "");
Иправил

2019-11-23 15:44 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
>  public class MainScreenFragment extends Fragment implements View.OnClickListener {
Исправил

2019-11-23 15:45 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        ArrayList<String> datesList = new ArrayList<>();
Исправил

2019-11-23 15:45 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        for (int i = 6; i >= 0; --i) {
Исправил

2019-11-23 15:45 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        String day = (String) DateFormat.format("dd",   c);
Исправил

2019-11-23 15:46 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +    private ArrayList<BarEntry> getData(){
Поправил везде

2019-11-23 15:47 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        BarData barData = new BarData(barDataSet);
Исправил

2019-11-23 15:49 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        XAxis xAxis = barChart.getXAxis();
Поправил

2019-11-23 15:50 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        String month = (String) DateFormat.format("MM", c);
Поправил

2019-11-23 16:01 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        barDataSet.setColors(Color.RED);
Еее, десигн
Сделал что-то типа светло-оранжевого цвета, вообще хз какой цвет взять, можно разные для каждого бара, но мне сказали тиммейты, что это еще хуже

2019-11-23 16:45 UTC, goddeuce1 commented on app/src/main/res/layout/main_screen_fragment.xml
>      <RelativeLayout
Изменил полностью, корневым остался RelativeLayout

2019-11-24 13:18 UTC, 102Rudy requested changes

2019-11-24 13:18 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +    private List<Integer> callsNumber;
лучше отделять статический константы от полей класса

2019-11-24 13:18 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        outState.putIntegerArrayList(CALLS_MAP_KEY, (ArrayList<Integer>)callsNumber);
List

2019-11-24 13:18 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        // Add "case" for each clickable element
useless comment

2019-11-24 13:18 UTC, 102Rudy commented on app/src/main/res/layout/main_screen_fragment.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
Кажется тут лучше использовать ConstraintLayout

2019-11-24 13:38 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        // Add "case" for each clickable element
Исправил

2019-11-24 13:39 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +    private List<Integer> callsNumber;
Исправил

2019-11-24 13:42 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/MainScreenFragment.java
> +        outState.putIntegerArrayList(CALLS_MAP_KEY, (ArrayList<Integer>)callsNumber);
Это приведение типа, сама переменная callsNumber имеет тип List<Integer>

2019-11-24 15:13 UTC, goddeuce1 commented on app/src/main/res/layout/main_screen_fragment.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
Поменял структуру, корневым сделал ConstraintLayout, убрал лишние LinearLayout-ы

2019-11-24 17:58 UTC, 102Rudy approved these changes

2019-11-24 18:00 UTC, merged