Details fragment
Lunex08/2019_android_git_reset_--hard pull request #7
Opened 2019-11-24 18:05 UTC by goddeuce1

2019-11-24 19:49 UTC, 102Rudy requested changes

2019-11-24 19:49 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReuseable.java
> +public class DetailsFragmentReuseable extends Fragment {
Reusable описка

2019-11-24 19:49 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReuseable.java
> +                    for (int i = 0; i < 10; ++i) {
magic number

2019-11-24 19:49 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReuseable.java
> +                    }
ну и в целом этот участок грубовато написан

2019-11-24 19:49 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReuseable.java
> +    class RecyclerAdapter extends RecyclerView.Adapter<RecyclerViewHolder> {
лучше не делать это как inner class фрагмента

2019-11-24 19:49 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReuseable.java
> +    class RecyclerViewHolder extends RecyclerView.ViewHolder {
лучше не делать это как inner class фрагмента

2019-11-24 19:49 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/MainActivity.java
> +                        .replace(R.id.fragment_details_content, detailsFragmentReuseable)
`R.id.fragment_details_content` - находит внутри фрагмента, а ты обращаешься к нему из Активити - это неправильно
Активити не должна управлять контентом фрагмента извне
это должен делать сам фрагмент

2019-12-03 16:32 UTC, 102Rudy requested changes

2019-12-03 16:32 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/MainActivity.java
> +        List<CallHistoryRecord> callHistoryRecords = callsModule.getCalls();
final ?

2019-12-21 18:38 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReuseable.java
> +public class DetailsFragmentReuseable extends Fragment {
Тупо, да)
Исправил

2019-12-21 18:38 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReuseable.java
> +                    for (int i = 0; i < 10; ++i) {
Выпилено

2019-12-21 18:39 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReuseable.java
> +                    }
Пока выпилено

2019-12-21 18:39 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReuseable.java
> +    class RecyclerAdapter extends RecyclerView.Adapter<RecyclerViewHolder> {
Вынесено в отдельный класс

2019-12-21 18:39 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/fragments/DetailsFragmentReuseable.java
> +    class RecyclerViewHolder extends RecyclerView.ViewHolder {
и это тоже

2019-12-21 18:39 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/MainActivity.java
> +                        .replace(R.id.fragment_details_content, detailsFragmentReuseable)
Это решило одну из проблем, связанную бекстеком)
Поправил.

2019-12-21 18:51 UTC, goddeuce1 commented on app/src/main/java/com/example/analyzer/MainActivity.java
> +        List<CallHistoryRecord> callHistoryRecords = callsModule.getCalls();
Final!

2019-12-22 09:44 UTC, 102Rudy approved these changes

2019-12-22 09:44 UTC, 102Rudy commented on app/src/main/java/com/example/analyzer/MainActivity.java
> +public class MainActivity extends AppCompatActivity implements MainScreenFragment.EventListener {
final

2019-12-22 11:22 UTC, merged